name: CI
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm linter:check
      - run: pnpm ts:check
      - run: pnpm test:run
